services:
  mysql:
    image: mysql:8.0
    container_name: corujazap_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: corujazap_db
      # MYSQL_USER: admin
      # MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --log-bin-trust-function-creators=1
    networks:
      - corujazap-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Aplicação CorujaZap
  app:
    build: .
    container_name: corujazap_app
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: corujazap_db
      DB_USER: root
      DB_PASSWORD: admin
    ports:
      - "8501:8501"
    volumes:
      - .:/corujazap
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - corujazap-net

# Volumes persistentes
volumes:
  mysql_data:
    driver: local

# Rede para comunicação entre containers
networks:
  corujazap-net:
    external: true